name: GitHub actions Terraform informations
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to get Terraform repository informations
branding:
  icon: feather
  color: gray-dark

runs:
  using: 'docker'
  image: 'Dockerfile'